server:
  port: 8004

spring:
  application:
    name: hystrix-provider-payment

eureka:
  instance:
    hostname: localhost
    instance-id: hystrix-provider-payment8004
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app.name: springcloud-alibaba
  company.name: www.ff.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
