server:
  port: 80

spring:
  application:
    name: eureka-consumer-order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  instance:
    hostname: localhost
    instance-id: consumer-order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
