server:
  port: 80

spring:
  application:
    name: eureka-consumer-order

eureka:
  instance:
    hostname: localhost
    instance-id: consumer-order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
