server:
  port: 8001

spring:
  application:
    name: provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.135:3306/test?serverTimezone=UTC
    username: root
    password: root123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengfan.springcloud.entity

logging:
  level:
    root: info
    com.fengfan.springcloud.dao: trace

eureka:
  instance:
    hostname: localhost
    instance-id: provider-payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

info:
  app.name: springcloud-alibaba
  company.name: www.ff.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
