server:
  port: 7002

spring:
  application:
    name: seata_order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.135:3306/seata_order?serverTimezone=UTC
    username: root
    password: root123
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.135:8848
    alibaba:
      seata:
        tx-service-group: fsp_tx_group

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengfan.springcloud.entity

logging:
  level:
    root: info
    com.fengfan.springcloud.dao: trace
